### ISSUE TITLE
php memory

### ISSUE THREAD

**Issue by gfernandez83** [CachetHQ/Cachet#1542]
memory exhausted on cachet while connecting to DB. I am using mysql. this happens while loading components and getting metric points via api. 

Feb 22 04:48:17 crm1 ool www: PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 196605 bytes) in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 335

**Comment by GrahamCampbell** [comment]
Please allocate more memory to PHP if you have lots of points to render.

**Comment by gfernandez83** [comment]
I put 4GB and it turn out ok in loading the components. but still having 500/504 error when getting the metric points via api. I have around 300k records on the metric points.

**Comment by jbrooksuk** [comment]
What version of Cachet are you using?

**Comment by gfernandez83** [comment]
2.2.0

**Comment by jbrooksuk** [comment]
So you're using the `master` branch?

**Comment by gfernandez83** [comment]
yes.

**Comment by jbrooksuk** [comment]
Ah it's the API endpoint, no problem. I'll have to look at this.

**Comment by gfernandez83** [comment]
btw, I only have 975 components. Does it really need such memory to load it?

**Comment by jbrooksuk** [comment]
> only 975 components

:trollface:

**Comment by gfernandez83** [comment]
thanks a lot.

**Comment by jbrooksuk** [comment]
This is fixed in v2.2. Should arrive this weekend.

**Comment by alexcroox** [comment]
Still having this issue in v2.2 when enabling a metrics graph, 100%+ CPU

Video http://cl.ly/fWyx

**Comment by GrahamCampbell** [comment]
The high cpu usage is normal for lots of data points.

**Comment by GrahamCampbell** [comment]
we have some improvements coming in 2.3

**Comment by alexcroox** [comment]
Are there any caching plugins currently? If only a handful of people visit my site with metrics enabled it brings the server to it's knees.

**Comment by GrahamCampbell** [comment]
All I can suggest is to put fewer points on the server, or get a more powerful server.

**Comment by jbrooksuk** [comment]
2.3 will allow you to store more values with less rows :)
