### ISSUE TITLE
Error 500 when accessing subscribers

### ISSUE THREAD

**Issue by henry-spanka** [CachetHQ/Cachet#1701]
Hi,
I have just upgraded my Cachet installation to version 2.2.0. Unfortunately when accessing the subscribers page I get a Server 500 error. PHP version is 5.6.19-0+deb8u1. Already tried to clear bootstrap cache and run any migrations.

Error Log(Pastebin): http://pastebin.com/qT69su7S

What could be the issue?

Thanks

**Comment by GrahamCampbell** [comment]
Try upgrading to the latest master. I think we fixed that.

**Comment by GrahamCampbell** [comment]
2.2.1-dev

**Comment by henry-spanka** [comment]
Thanks. Unfortunately the issue still exists. Upgraded to master, cleared bootstrap cache and ran migrations. Any clue?

**Comment by GrahamCampbell** [comment]
Looks like a bug in our code then. Thanks for reporting.

**Comment by GrahamCampbell** [comment]
NB, never manually run migrations. Always run the `php artisan app:update` command, and it'll do everything.

**Comment by henry-spanka** [comment]
Yeah, i meant that ;) I ran `php artisan app:update`

**Comment by GrahamCampbell** [comment]
Ok, cool. I've assigned this for James to look into.

**Comment by jbrooksuk** [comment]
@joecohens is actively working on a rewrite of the Subscriber code, this will be fixed shortly.

**Comment by henry-spanka** [comment]
Why have you closed this issue? I can not see any commit fixing this.

**Comment by GrahamCampbell** [comment]
Because there's already an open issue for this.

**Comment by henry-spanka** [comment]
Ah okay, would be nice if you could reference it ;)

**Comment by jbrooksuk** [comment]
@joecohens is actively working on it.
