### ISSUE TITLE
Line breaks not working in maintenance or incidents messages

### ISSUE THREAD

**Issue by giezi** [CachetHQ/Cachet#2059]
Before submitting your issue, please make sure that you've checked the checkboxes below.
- [x ] I am running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x ] I am running at least PHP 5.5.9. _You can check this by running `php -v`._
- [x ] I have ran `rm -rf bootstrap/cache/*`.
### Expected behaviour

The line breaks (from the planned maintenance) are not correctly displayed on the main status page in the customer view and in the notification email.

The view in the admin panel looks as it should:

<img width="786" alt="screen shot 2016-08-15 at 17 22 44" src="https://cloud.githubusercontent.com/assets/1326203/17669250/39b1880c-630d-11e6-9752-c2b0d29802dc.png">

On the status page, the maintenance or incidents message doesn't contain any line breaks:

<img width="951" alt="screen shot 2016-08-15 at 17 21 30" src="https://cloud.githubusercontent.com/assets/1326203/17669278/5bee853c-630d-11e6-9a67-34dc49c56b48.png">
### Actual behaviour

Line breaks are not correctly displayed in HTML.
### Steps to reproduce
1. Create a new incident or maintenance with line breaks

**Comment by TheLastProject** [comment]
This is correct behaviour, as the input field is Markdown. Markdown strips newlines. If you want to add a newline, add two spaces at the end of the previous line. It's one of the not so clean parts of Markdown.

**Comment by jbrooksuk** [comment]
@TheLastProject true, but it's annoying and misleading. Like HackerNews...

I've changed soft breaks to default to the expected behaviour.

**Comment by TheLastProject** [comment]
Can definitely agree that breaking the Markdown standard here is acceptable, yeah.

**Comment by giezi** [comment]
Hi there

many thanks for your answers and your hint :)
We have added the two spaces, in the incident window it looks fine, but the exactly the same content in the maintenance window looks like this:

<img width="951" alt="screen shot 2016-08-15 at 17 36 54" src="https://cloud.githubusercontent.com/assets/1326203/17669744/1f982ae6-630f-11e6-8805-5575aa39088a.png">

Thanks!

**Comment by williamsdb** [comment]
I agree that this doesn't work in the maintenance screen so would seem to be a bug.

**Comment by jbrooksuk** [comment]
@williamsdb I think you need to bring this up with [CommonMark](https://github.com/thephpleague/commonmark).

**Comment by williamsdb** [comment]
Except that you use the same component on reporting an incident and recording maintenance and they give different results. That sounds more like a Cachet problem to me. Happy to provide more information but it is exactly as @giezi said in his post.

**Comment by jbrooksuk** [comment]
@joecohens reckon this could be a CSS thing?

**Comment by joecohens** [comment]
If I'm not wrong, we are not using the `markdown-body` class on the schedules https://github.com/CachetHQ/Cachet/blob/2.3/resources/views/partials/schedule.blade.php#L8 I'm guessing that's the problem

**Comment by jbrooksuk** [comment]
This should now be fixed.

**Comment by jbrooksuk** [comment]
https://github.com/CachetHQ/Cachet/commit/b3fc690d1d5af33814afab57c66521ee7b3db845

**Comment by williamsdb** [comment]
What version is this in as just updated to 2.3.9 and still occurs there. Thanks

**Comment by williamsdb** [comment]
FYI had to remove the bootstrap cache for this to take effect.

**Comment by jbrooksuk** [comment]
Also, `php artisan view:clear` may have worked too?

**Comment by williamsdb** [comment]
Quite possibly yes but I just followed the upgrade instructions and when it didn't work force cleared the cache.
