### ISSUE TITLE
Email is sending last component status, not new.

### ISSUE THREAD

**Issue by TheEpTic** [CachetHQ/Cachet#2198]
When setting the component to "Operational" - It will email the status update, but will inform me of the last status.

> The component Chat has seen a status change. The component is now at Performance Issues.

^ After setting it to "Operational"

I am running the latest Git pull

**Comment by jbrooksuk** [comment]
This has been fixed on the 2.4 branch (currently under development). Apologies for the annoyance here.

@GrahamCampbell perhaps we backport this fix into v2.3?

**Comment by TheEpTic** [comment]
I updated to the 2.4 branch when you posted this. After some testing I found the issue is still there.

**Comment by jbrooksuk** [comment]
I wouldn't rely on the 2.4 branch.
