### ISSUE TITLE
Wrong timestamps in metric points

### ISSUE THREAD

**Issue by PietsHost** [CachetHQ/Cachet#2459]
actually I'm using v2.4.0-dev (installed yesterday).

So far, everything is OK but the metric points.. 

i've checked everything now, but I can't figure out, where the problem is.

I post a new metric point:
`curl -H "Content-Type: application/json;" -H "X-Cachet-Token: XXXXXXXXX -H "Time-Zone: Europe/Berlin" --request POST --url https://mypage.de/api/v1/metrics/3/points --data '{"value":100}'`

the return is:
`{"data":{"value":100,"counter":1,"metric_id":3,"updated_at":"2017-03-22 19:14:14","created_at":"2017-03-22 19:14:14","id":7,"calculated_value":100}}`

in mysql "SELECT CURRENT_TIME" returns:
`CURRENT_TIME
19:15:48`

```
[root@myhost]# date
Mi 22. Mär 19:15:31 CET 2017
```

BUT: the metric points are stored to the DB with 1h time difference:
```
created_at
2017-03-22 18:14:14
```

```
updated_at
2017-03-22 18:14:14
```

**Comment by OzWookiee** [comment]
I had a similar issue and it was resolved but making sure that MySQL had the correct Timezone tables installed which do not come default and need to be installed separately.

See here; https://github.com/CachetHQ/Cachet/issues/2373

**Comment by PietsHost** [comment]
I've seen your issue before I posted my issue :)

Timezone is set, but the problem still exists

**Comment by OzWookiee** [comment]
Ahh well, sorry that didn't work for you.

**Comment by jbrooksuk** [comment]
@CachetHQ/core should we maybe be storing dates as `dateTimeTz`?

**Comment by jbrooksuk** [comment]
@joecohens any idea?

**Comment by jbrooksuk** [comment]
@GrahamCampbell maybe?

**Comment by Kostecki** [comment]
I have the exact same problem. Select NOW(); and CURRENT_TIMESTAMP both show the right values in the database, as well as date on the server, but all of the timestamps in the database entries by cachet is an hour off.

Does anyone have a solution?

**Comment by jbrooksuk** [comment]
Could you pull down the latest version now and set `APP_TIMEZONE` to your timezone and try again please.

**Comment by Kostecki** [comment]
My Cachet installation of 2.4 is fully updated as of right now. With database saying "Europe/Copenhagen" as the value of app_timezone. 
Entries are still an hour behind, i'm afraid.

**Comment by AEnterprise** [comment]
i'm having the same issue here, my database,VPS clock and app timezone are both set to "Europe/Brussels" (so UTC+1) but when inserted into the database the timestamp corresponds to UTC instead. i had to change things to show in UTC instead to make it not have the last hour blank

is there any other information or logs i could provide to help track this down so it can be fixed?

**Comment by GameMaster2030** [comment]
Yeah, I have the same issue. My metrics are one hour behind.

**Comment by flestorres** [comment]
Having the same issue, is there any workaround for this one? Metrics are 8 hours behind.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
