### ISSUE TITLE
Edit Scheduled Maintenance

### ISSUE THREAD

**Issue by gonzoinc** [CachetHQ/Cachet#2509]
When Editing an existing Scheduled Maintenance entry, the page is auto filling the last date field to 0001-11-29 19:00 Which is causing all sorts of issues, Saving it with that date field populated removes the event as being completed form the main page, Clearing the date field out looks to do the same thing. Since the datepicker looks to only allow dates to be cycled through 10 at a time, it would take forever to get from the year 0001 to 2017, Luckily manual entry does work.

The date completed field should not even show or be required until the selection marking the event completed has been selected.

Screenshot:
![screen shot 2017-05-01 at 1 44 42 pm](https://cloud.githubusercontent.com/assets/27728728/25588343/ed02967e-2e75-11e7-868c-b486767096cf.png)

**Comment by jbrooksuk** [comment]
@gonzoinc thanks for the report! What version of Cachet are you using?

**Comment by jbrooksuk** [comment]
Also, what browser are you using?

**Comment by jbrooksuk** [comment]
Fixed :)

**Comment by gonzoinc** [comment]
I cherry picked your changes and it did not fix the issue. When editing the Maintenance Event the date is still showing the '0001-11-29 19:00'. When you save the event after making updates it is still saving that date into the DB which entail removes the event form the main dashboard.

**Comment by gonzoinc** [comment]
I did some testing with this by removing the below from the "Completed At" input:

`value="{{ $schedule->completed_at_datetimepicker }}"`

This stopped the weird data from being auto entered into the field value but this exposed a second problem. Now when you edit the existing Maint event it still gets removed from the main dashboard. Going to dig through the DB data and see what values are actually changing and causing the event to be removed from the main dashboard.

**Comment by gonzoinc** [comment]
Found  the problem, not sure how to fix it..... not that familiar with the code base just yet.

When you go in and edit a Maint event, if you actually make a change and save, the "Scheduled For" date gets changed to the current date/time which removes it from the main dashboard view as the view only looks for events in the future.  if you makes changes and change the "Scheduled For" Datetime then it does save properly. It only breaks if you make a change to an existing event and don't make a change to the "Scheduled For" date/time.

**Comment by apssupport** [comment]
@gonzoinc Thank you for bringing this up, I can confirm that I am experiencing the same issue.

**Comment by jbrooksuk** [comment]
Hmm, looks like the `created_at` field isn't `null` in the database when it's left empty.

**Comment by gonzoinc** [comment]
Still not completely resolved. The Maint completed date looks fine now, but when you go in an edit a future event, after you save the changes the event gets removed from the main status page.

The problem is that when you actually make a change and save, the created date gets saved as the current date/time which is dropping it from the main status page.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
