### ISSUE TITLE
2.4 installation fails on Alpine Linux

### ISSUE THREAD

**Issue by koendc** [CachetHQ/Cachet#2586]
The installation of cachet 2.4 on Alpine Linux fails:
```
> php artisan optimize

                                                               
  [ErrorException]                                             
  Use of undefined constant GLOB_BRACE - assumed 'GLOB_BRACE'  
                                                               

Script php artisan optimize handling the post-install-cmd event returned with error code 1
```
GLOB_BRACE is not supported on musl-based systems - see https://github.com/zendframework/zend-stdlib/issues/58.

This line is possibly related:
https://github.com/CachetHQ/Cachet/blob/2.4/app/Foundation/Providers/RouteServiceProvider.php#L92

**Comment by jbrooksuk** [comment]
This is now fixed :)

**Comment by koendc** [comment]
This is still an issue: on Alpine, none of the routes is found and you get 404's for all requests.
