### ISSUE TITLE
Updates on components alert subscribers even when the status is unchanged

### ISSUE THREAD

**Issue by ferrerluis** [CachetHQ/Cachet#2683]
So I am using Cachet in kind of a non-orthodox way. I have apps update their own status and then I have a job that checks when a component hasn't been updated for more than 5 min and marks it as having a partial/major outage.

The problem is: every time a component gets updated from "Operational" -> "Operational," it still triggers an email to all subscribers, just to tell them that the system is STILL operational. This results in dozens of emails every 5 min (or less) with no useful information.

I think it would be wise to have Cachet send emails only when the status has changed during a component update.

Thoughts?

**Comment by misuto** [comment]
I have the exact same problem. I'm using the Uptimerobot script to check server availability.
Maybe its as easy as to check if the "new" status is equal to the old status, then we don't do anything.

**Comment by jbrooksuk** [comment]
What version are you using?

**Comment by jbrooksuk** [comment]
This was fixed in https://github.com/CachetHQ/Cachet/commit/b40066b

**Comment by squaricdot** [comment]
Still experiencing this issue with after setting everything up and writing a script i am experiencing this issue.
cachet_ver=2.3.15

cachet is sending out mails for updated component even when the status hasn't changed.

this makes the whole product basically unusable.

**Comment by aiso-net** [comment]
Any fix to this on the 2.3 branch, i'm having this issue as well?
