### ISSUE TITLE
New line not maintained in incidents and maintenance (both in the email and on the UI)

### ISSUE THREAD

**Issue by labolanimichele** [CachetHQ/Cachet#2712]
When creating a new incident or a new scheduled maintenance, I as an admin indent the text with new lines, so to make the communication look better to the users.

However, this indentation is not maintained in the email, nor in the UI (partially).
The key issue is however in the email, as shown below.

See attached screenshots:

_Creation of the incident - inserting new lines_
![newline_create](https://user-images.githubusercontent.com/22618797/30318103-69d9c4c0-97ac-11e7-9779-06158f324e15.PNG)

_Email notification - no new lines included_
![newline_email](https://user-images.githubusercontent.com/22618797/30318119-7951ea18-97ac-11e7-8c45-2771638305a3.PNG)

_UI Notification - it seems that 2 new lines appear as a single new line. Single new lines are instead ignored._
![newline_ui](https://user-images.githubusercontent.com/22618797/30318139-88ecc236-97ac-11e7-89df-3ddfd781a8c9.PNG)

I believe 2.3(.6?) don't remember which one I had tried) was not showing this issue in the email...

Thanks!
Michele

**Comment by nixmomo** [comment]
do you used markdown syntax? If not, try it out. That fixed it for me

**Comment by labolanimichele** [comment]
Hi Nixmomo,

did it solve the issue also in the email?
Markdown works for me in the UI (hence the 2 new lines becoming 1, which is ok), but does not work in the email notification, where markdown seems not to be recognized.

**Comment by nixmomo** [comment]
yup it worked in my 2.4. installation for both. i checked it and all new lines are in mailings too

**Comment by jbrooksuk** [comment]
2.4 should fix this :)

**Comment by labolanimichele** [comment]
just pulled the very last 2.4, still not working on the email for me. On the status page it looks perfect, but in the email I get plain text without any indentation at all.
@nixmomo , do you have the very last 2.4?
Could it be that something got changed during 2.4 development?
