### ISSUE TITLE
New line / Markdown not maintained in incidents and maintenance 

### ISSUE THREAD

**Issue by labolanimichele** [CachetHQ/Cachet#2935]
Hello,

sorry to reopen this one, but on the latest pull of 2.4 it still does not work for me (pulled today).

Please see attached the template, what is shown in the status page (which is perfect) and what I receive by email (which is not working for me).

Any hint? It may be something trivial I cannot see...
This is currently the only thing which is preventing us from using Cachet for our customer notifications., which is a pity!

Thank you, 
Michele

![template](https://user-images.githubusercontent.com/22618797/37356790-14f7db8e-26e7-11e8-8eab-8f2a9ebbe27b.PNG)
![incidentstatuspage](https://user-images.githubusercontent.com/22618797/37356791-1526aff4-26e7-11e8-99aa-6a34f3d41edb.PNG)
![incidentemail](https://user-images.githubusercontent.com/22618797/37356792-154c0d8a-26e7-11e8-8143-f796c2635861.PNG)

**Comment by labolanimichele** [comment]
(I had already opened it in #2712, but I still see the same problem)

**Comment by jbrooksuk** [comment]
Looks like the emails don't support Markdown.

**Comment by anthonybocci** [comment]
I read the [Laravel documentation][1] and I saw that the message had a `markdown` method. Perhaps we could use it in `app/Notifications/**/*.php`?

[1]: https://laravel.com/docs/5.6/mail

**Comment by jbrooksuk** [comment]
This should be fixed now.

**Comment by uxen-ab** [comment]
@jbrooksuk I think this issue can be reopened, d63b9b2b3c2517b7e81f4fb6cb75494ef3cdab37 seems don't fix it.
This issue was fixed, but by removing the line `markdown` in 0c96e6767853dff7697498863130719a7cffe9fa the markdown is no longer interpreted and all the text is on one line, as pointed on Slack by sontt.

**Comment by jbrooksuk** [comment]
> @jbrooksuk I think this issue can be reopened, d63b9b2 seems don't fix it.

@uxen-ab what do you mean it's not fixed, sorry? We should be stripping out all HTML/Markdown.

**Comment by uxen-ab** [comment]
@jbrooksuk I have not experienced this issue, it's `sontt`, on Slack, that reported it to me, with screenshots. During the week on Slack I'll ask him to explain more here.
He sent me a screenshot where its email was in this issue, markdown not interpreted and line breaks either.

**Comment by sontt710** [comment]
Hi,

I created an incident to notification via email, but in an email no new line break, but dashboard work fine.

![image](https://user-images.githubusercontent.com/31494976/38180118-45535f70-3654-11e8-8cf0-6fe1dbe9f0c0.png)
![image](https://user-images.githubusercontent.com/31494976/38180126-4c5ab57a-3654-11e8-883e-68e8bf4aef18.png)

**Comment by jbrooksuk** [comment]
This will be fixed in https://github.com/CachetHQ/Cachet/pull/3100
