### ISSUE TITLE
Datepicker design issue

### ISSUE THREAD

**Issue by anthonybocci** [CachetHQ/Cachet#3143]
When picking a date, the datepicker seems to have problem with its design. The hour/minute take some width so the date have no much space. 
I've experienced it on the maintenance creation.

<img width="332" alt="cachet-maintenance-datepicker" src="https://user-images.githubusercontent.com/7780244/42081888-e789729e-7b86-11e8-8011-cfbbd494bf51.png">

Cachet version 2.4 (6e8821986e48c2cc091889aaa125e115674d7167)
Browser Firefox 63.0a1 (2018-06-28) (64 bits) OSX

**Comment by krollebol** [comment]
I also noticed this issue with the datapicker.
But also when trying to delete a maintenance, incident or component it doesn't work. It looks like the popup is not showing correctly. Maybe a missing javascript.

On latests git 2.4 version 
Tested in Firefox and Chrome.

**Comment by jbrooksuk** [comment]
Thanks for reporting guys. I’ll fix this tonight.

**Comment by jbrooksuk** [comment]
All fixed up!

I've replaced `bootstrap-datetime-picker` with Flatpickr which is much better.

**Comment by jbrooksuk** [comment]
Closed by d0b802d82f18fded5851b02ea3b833275d4c52c4

**Comment by krollebol** [comment]
Hi,
I've update to the latest. But now no datapicker is showing, and the data field is read-only, so manual input is also not possible. This is how the pages looks ....
![image](https://user-images.githubusercontent.com/15714698/42160715-8c5fda9c-7df8-11e8-815f-726502334c48.png)

**Comment by jbrooksuk** [comment]
I believe this is because of PurgeCSS. I'll see if I can get it to ignore.

**Comment by jbrooksuk** [comment]
Fixed in 1dfcd9aa

**Comment by Atriusftw** [comment]
I'm sorry that i'm commenting on a closed issue, but it seems like the problem still exists after the fix.
I've pulled the latest changes from 2.4, ran `rm -rf bootstrap/cache/*` and `php artisan cache:clear` in addition to clearing cache client side without any noticable changes.

**Comment by jbrooksuk** [comment]
Can you try clearing your browser cache please? #3151 was also affected by this issue but is now resolved.

**Comment by jbrooksuk** [comment]
😝
