### ISSUE TITLE
Website cannot force ssl

### ISSUE THREAD

**Issue by Mooash** [cachethq/Cachet#374]
I've set the website URL to https://status.example.com/ yet it keeps linking the http variant. It makes it really hard to deploy this whilst forcing https.

**Comment by jbrooksuk** [comment]
By this, do you mean that the assets are loading over `http`?

**Comment by Mooash** [comment]
Yeah sorry, so even if I make the URL https://status.example.com it links everything with http links (images/JS etc) and links to the other pages are all http instead of https

**Comment by jbrooksuk** [comment]
Ah right, yes we're aware of this issue. @noahbass has been looking into it I believe.

**Comment by jbrooksuk** [comment]
@GrahamCampbell last time I removed all of the `url` helpers in `master.blade.php` you said something about it needing to be there. What's the reason, was it sub-folder support?

**Comment by jbrooksuk** [comment]
@Mooash sorry for the very long delay. The status page itself is all HTTPS, so is login. I'm going to go through all of the dashboard and make it compatible, then we should be good to close this issue. Thanks!

**Comment by GrahamCampbell** [comment]
@Mooash It's likely this is caused by you not setting your rusted proxies correctly.

**Comment by jbrooksuk** [comment]
@GrahamCampbell the trusted proxies thing doesn't seem to be working.

**Comment by GrahamCampbell** [comment]
> the trusted proxies thing doesn't seem to be working.

It works for me? Possibly bad nginx/apache config then?

**Comment by jbrooksuk** [comment]
Does it work on Heroku for you buddy?

**Comment by GrahamCampbell** [comment]
Not a clue, sorry.

**Comment by Mooash** [comment]
Whoops, I missed this stuff! Let me do another test and see what happens.

**Comment by jbrooksuk** [comment]
Looks like this has creeped back in (in a couple of places), see #499 - but this itself should be fixed.

**Comment by joaquin386** [comment]
Hey guys adding APP_URL=https://my.site.com (docker image) still have the issue than when accessing https://my.site.com it replies to a redirection:
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="1;url=http://site.company.com/setup" />

        <title>Redirecting to http://site.company.com/setup</title>
    </head>
    <body>
        Redirecting to <a href="http://site.company.com/setup">http://site.company.com/setup</a>.
    </body>
</html>
