### ISSUE TITLE
Webhooks don't work

### ISSUE THREAD

**Issue by egelhaus** [cachethq/cachet#4532]
When I create an webhook, it works fine, but when I create an incident it return an 500 Error Code, doesn't send it but creates the Incident.
Same with deleting and updating it, it doesn't even try.

Version: v3
System: Ubuntu 24.04
Running after an reverse proxy (nginx); SSL
PHP: 8.3

Note: I had to manually edit the apache2 config to automatically switch to SSL else it didn't work.
Note2: I don't know how to check the logs, if you say how i'll provide it.

**Comment by egelhaus** [comment]
Hello?
Anybody?

**Comment by jbrooksuk** [comment]
@egelhaus sorry for the delay, it's been a very busy few weeks!

Could you send us the logs, which you should be able to find in `storage/logs`.

Also, make sure that you're running the queue workers (`php artisan queue:work`).

**Comment by egelhaus** [comment]
Hey @jbrooksuk ,
Absolutely no problem for the delay.
Here is an pastebin with the logs, as it is so big I cannot paste it here: https://pastebin.com/AWXE0hz3
And here is my .env for further information that you may want to know: https://pastebin.com/S3T8LpCR
And I use SQLite

When executing "php artisan queue:work" it just gets stuck at " INFO  Processing jobs from the [default] queue."

Thanks in regards

**Comment by egelhaus** [comment]
Anyone?

**Comment by jbrooksuk** [comment]
@egelhaus sorry I was on holiday the last week. I see the error; you need to run `php artisan make:queue-table` and then run `php artisan migrate`. This should fix it for you.

**Comment by egelhaus** [comment]
Hey,
I ran the command and the 500 internal Error Page goes away after creating Incidents or anything else, it still shows no attempts / it doesn't send anything. I'm using a discord web hook by the way. I will provide the logs in a second. (I will edit them into this message)
Edit: I had to manually delete the log file as it was way too big for me to copy, I did hid before but now it doesn't generate any new Logs.

**Comment by jbrooksuk** [comment]
Okay, so now you need to have a daemon running `php artisan queue:work`.

**Comment by egelhaus** [comment]
Hey @jbrooksuk 
Alright, it does try to post the web hook, it displays it in the logs when running the daemon, and shows DONE, but nothing arrives and under Attempts it says the attempt failed, maybe it is because of the forced secret, and discord doesn't accept that?
This time logs have been generated: https://pastebin.com/PRpYNbcM

**Comment by egelhaus** [comment]
Hey,
I was able to resolve it, just not the way I expected / wanted.
I was able to resolve it by forwarding it though n8n but it looks like the web hook feature just doesn't have enough potential right now for me that I can use it. For example it doesn't give the Components affected in the payload.
Thank you very much for your help @jbrooksuk but right now I won't use the feature but looking forward of using it later when the web hook gets more features / compatibility with 3rd parties.

**Comment by jbrooksuk** [comment]
@egelhaus we can add the list of components affected in the payload. Leave it with me!

**Comment by egelhaus** [comment]
Hey @jbrooksuk 
That would be awesome!
It would also be nice if the "secret" at configuring webhooks wouldnt be mandatory, that would fix a lot of problems.

**Comment by jbrooksuk** [comment]
@egelhaus is there a reason you're not able to configure a secret? The same payload is still sent, but it means you're able to verify the request on the receiving side.

**Comment by egelhaus** [comment]
Well, because Discord doesn't Support it, and when trying without an secret configured in n8n it doesn't work, with an secret it works.
So it shouldn't be mandatory

**Comment by egelhaus** [comment]
Would you be able to implement that @jbrooksuk ?
