### ISSUE TITLE
Style bug in date picker

### ISSUE THREAD

**Issue by dennusb** [cachethq/Cachet#675]
Hi,

When i create an incident (or scheduled maintenance) and i click the date picker this is what happens :
![screen shot 2015-05-27 at 14 32 35](https://cloud.githubusercontent.com/assets/666126/7835989/4bd6a91c-047d-11e5-8ed2-1b670dc23567.png)

I think it's a styling bug or something? I'm using OSX and the latest Chrome!

**Comment by jbrooksuk** [comment]
I've updated the datetimepicker that we use :) also it's now styled with the Cachet green.

![image](https://cloud.githubusercontent.com/assets/246103/7861037/a033fd2a-0545-11e5-8945-fffe14e01594.png)

This should fix the issue you were experiencing.

**Comment by dennusb** [comment]
After update we are still experiencing this issue. It is now green styled, but still at the top of the page, while the input box is way lower...

**Comment by TheoBearman** [comment]
I have been experiencing the same issue. However, that is a separate issue to the styling addressed in this issue.

**Comment by jbrooksuk** [comment]
Looks like it's a screen size issue:

![image](https://cloud.githubusercontent.com/assets/246103/7861338/6a7358c8-0547-11e5-8969-e05c7ce4f7c6.png)

**Comment by TheoBearman** [comment]
It is James. If you zoom out Chrome, as I have been doing,, the box appears in fll. Maybe we need to change the dimensions of the box to change with the screen resolution.

**Comment by dennusb** [comment]
I'm working on an Macbook with 2560 by 1600 pixels (Retina). Working in Chrome!

**Comment by jbrooksuk** [comment]
This is a tougher issue. Leave it with me.

**Comment by dennusb** [comment]
Thanks !!

**Comment by dennusb** [comment]
Already an update on this issue?

**Comment by jbrooksuk** [comment]
I'll try and get this fixed before we ship on Friday :)

**Comment by jbrooksuk** [comment]
FWIW I can only recreate this issue like this:

![image](https://cloud.githubusercontent.com/assets/246103/8183057/1f15cbbe-142d-11e5-8eff-877e0aeef3a6.png)

**Comment by TheoBearman** [comment]
@jbrooksuk See screenshot below. I think it may have something to do with the screen resolution of the PC viewing Cachet.

Btw... what is being shipped on Friday? V1?!

![dsj](https://cloud.githubusercontent.com/assets/6546590/8183161/132fd154-142e-11e5-8494-6b65710af798.png)

**Comment by dennusb** [comment]
Thankyou @jbrooksuk

**Comment by dennusb** [comment]
Yeah it is a resolution thing. If i change the zoom-level in Chrome it goes back to 'normal'

**Comment by jbrooksuk** [comment]
Thanks for the info guys, this really helps :)

@TheoBearman yes, V1 ;)

**Comment by jbrooksuk** [comment]
It only seems to go out of place for me when I show the component options...

**Comment by dennusb** [comment]
I always have the issue... with or without the component options :(

**Comment by TheoBearman** [comment]
YAYAYAYAYAYAY @jbrooksuk!

Can we make sure there are suitable docs showing up to upgrade to V1 from the current `Master` branch?

With regards to this, maybe we need to set the box to have dynamic dimensions depending on the screen resolution available. I can confirm the same issue as @dennusb. Maybe we just need to make the box appear over, or near to, the `When did this incident occur?` line instead of at the top of the page.

**Comment by jbrooksuk** [comment]
The docs at https://docs.cachethq.io are actually quite full :) The API docs are (I think) 100% complete. Is there anything more you'd like to see? Send me an email james@cachethq.io and we can discuss more.

What's weird is that the calendar should be bound to the date input anyway...

**Comment by TheoBearman** [comment]
@jbrooksuk How is V1 being released? Will the `Master` branch become a `V1` branch, in which case I can just pull the branch like I have been doing at the moment. Or, it it going to need a completely fresh install?

That is weird. Evidently it's not being bound to the date input as it should!

**Comment by jbrooksuk** [comment]
@TheoBearman that's a good question. @joecohens and I are Skyping tonight to discuss release and some future stuff, so we'll discuss this.

This is what I'm seeing:
![0gwdozctfg](https://cloud.githubusercontent.com/assets/246103/8183348/5038a390-142f-11e5-8fe7-be15d831ffc9.gif)

**Comment by TheoBearman** [comment]
@jbrooksuk I can confirm on Chrome, when I start a new incident, without filling in any of the information and just clicking the date option, the box automatically appears at the top of the page, as my previous screenshot would suggest.

I am on a school computer currently so this is a Chrome issue at least rather than a problem just with my PC. What browser are you using @jbrooksuk?

**Comment by jbrooksuk** [comment]
Also Chrome.

**Comment by TheoBearman** [comment]
@jbrooksuk Then it must be Windows vs Mac.

**Comment by jbrooksuk** [comment]
I don't believe that's the case because it's more of a position thing.

**Comment by TheoBearman** [comment]
@jbrooksuk I'll leave it in your capable hands. It is strange however that Cachet is behaving differently in the Windows and Mac versions of Chrome.

**Comment by jbrooksuk** [comment]
I've found the cause of it. If you remove the `well` class from within `#component-status` it works. But if you add something on to it, like `panel` it'll break...

**Comment by TheoBearman** [comment]
@jbrooksuk Fixable?

**Comment by dennusb** [comment]
You found it. Cooool :D

**Comment by jbrooksuk** [comment]
I think so... Just having a play.

**Comment by jbrooksuk** [comment]
Urgh, I think I know why, but the fix means I have to go through **every. single. form**. I'll keep playing.

**Comment by dennusb** [comment]
Jeeezz, what do you think it is?

**Comment by jbrooksuk** [comment]
Actually, for V1 I'm going to take the lazy route out - it'll still work though.

**Comment by TheoBearman** [comment]
@jbrooksuk So this will be fixed on Friday but not before?

**Comment by TheoBearman** [comment]
@jbrooksuk LOL, just as I post that comment, you fix it!

**Comment by jbrooksuk** [comment]
I've fixed it, but it means the component picker isn't as pretty.

V2 will have a completely new dashboard and some other changes that'll prevent this from happening.

**Comment by TheoBearman** [comment]
@jbrooksuk The only thing that the fix has done is display the month at the top of the date picker without me having to scroll out. The date picker itself is still not fixed to the `When did this incident occur?` section of the incident form, it is still fixed to the top of the screen. Was that the intention of the fix?

**Comment by jbrooksuk** [comment]
Screenshot?

**Comment by jbrooksuk** [comment]
The issue I was having doesn't occur anymore, so I thought it'd fix the issue for you guys too.

**Comment by TheoBearman** [comment]
![dsj](https://cloud.githubusercontent.com/assets/6546590/8184132/a22b2ff6-1434-11e5-82e0-481cfb26aa8c.png)

**Comment by dennusb** [comment]
Even weirder : After pulling the latest source i now get :

[Tue Jun 16 15:33:34 2015] [error] [client 172.16.2.188] PHP Fatal error:  Uncaught exception 'Illuminate\\Contracts\\Container\\BindingResolutionException' with message 'Unresolvable dependency resolving [Parameter #0 [ <required> $path ]] in class GrahamCampbell\\Exceptions\\ExceptionInfo' in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php:823\nStack trace:\n#0 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(798): Illuminate\\Container\\Container->resolveNonClass(Object(ReflectionParameter))\n#1 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(771): Illuminate\\Container\\Container->getDependencies(Array, Array)\n#2 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\\Container\\Container->build('GrahamCampbell\\\\...', Array)\n#3 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(642): Illuminate\\Container\\Container->make('GrahamCampbell\\\\...', Array)\n#4 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 823

**Comment by jbrooksuk** [comment]
What did you run @dennusb

**Comment by jbrooksuk** [comment]
@TheoBearman I hate this calendar widget.

**Comment by dennusb** [comment]
Just git pull and then the composer.phar install --no-dev --no-scripts & composer.phar install --no-dev -o ?

**Comment by jbrooksuk** [comment]
You can `composer install` twice?

**Comment by dennusb** [comment]
That's what you guys said i should do in another call :P

**Comment by jbrooksuk** [comment]
Ah, yeah @GrahamCampbell told you to do it to fix another issue.

Try running `composer.phar du`

**Comment by dennusb** [comment]
Did not fix it :(

**Comment by TheoBearman** [comment]
@jbrooksuk I hate it too.

**Comment by dennusb** [comment]
Fixed it by removing everything and pulling the repo again.
But indeed, the datepicker thingy is not fixed :(

**Comment by jbrooksuk** [comment]
It looks like a few people are having issues with the date picker on other projects. V4 introduced some kind of "smart" placement system, but it doesn't work.

**Comment by dennusb** [comment]
Replace the date picker with another? Or is that too much hassle?

**Comment by jbrooksuk** [comment]
None are "as good" and I use that term loosely.

**Comment by TheoBearman** [comment]
@jbrooksuk So this is a Lavarel issue?

**Comment by jbrooksuk** [comment]
Not a Laravel issue, sorry the V4 is kind of confusing. I meant version 4 of the datepicker :)

**Comment by TheoBearman** [comment]
@jbrooksuk So can we just use V3?

**Comment by jbrooksuk** [comment]
That's what I'm going to try later :)

**Comment by jbrooksuk** [comment]
Unless you want to give it a go?

**Comment by TheoBearman** [comment]
@jbrooksuk Wouldn't know where to start. Never had any experience with Lavarel.

**Comment by jbrooksuk** [comment]
No problem @TheoBearman I'll try and fix this later on :)

**Comment by TheoBearman** [comment]
@jbrooksuk Cheers.

**Comment by jbrooksuk** [comment]
Hmmm... Pull down `master`? Quicker than I thought it would be.

**Comment by TheoBearman** [comment]
You just can't get away from fixing issues, even for a few minutes, can you?!

Working. Good stuff.

**Comment by jbrooksuk** [comment]
:+1:

**Comment by jbrooksuk** [comment]
It bugs me if there is an issue that I can't fix :)

**Comment by TheoBearman** [comment]
@jbrooksuk I can tell.
