### ISSUE TITLE
Unsubscribe is dead

### ISSUE THREAD

**Issue by dennusb** [cachethq/Cachet#697]
Hi,

The unsubscribe link in the incident mail is dead. It links to /unsubscribe but i get a : Symfony \ Component \ HttpKernel \ Exception \ NotFoundHttpException

**Comment by dennusb** [comment]
In the routes i can see that there is a route for /unsubscribe/{code}, but the e-mail is not attaching the code to the URL!

**Comment by jbrooksuk** [comment]
Should be fixed now.

**Comment by dennusb** [comment]
Still not working... link text is now "Unsuscribe from email updates." but the link is still "/unsubscribe" without an token!

**Comment by jbrooksuk** [comment]
My bad, this should be fixed now :)
