### ISSUE TITLE
Cannot create incident or metric

### ISSUE THREAD

**Issue by unixengineer** [cachethq/Cachet#765]
I am trying to create an incident, and it is failing with bad request

Post:
```
POST /api/v1/incidents HTTP/1.1
Content-Type: application/json
accept-encoding: gzip
X-Cachet-Token: 7lipnzcreXL2eXQTYS9a
Accept: */*
Host: 10.0.1.100
Connection: close
User-Agent: Paw/2.2.2 (Macintosh; OS X/10.10.3) GCDHTTPRequest
Content-Length: 85

{"name":"Monkey Farts","message":"The title says it all","status":1,"component_id":1}
```
Reponse:
```
HTTP/1.0 400 Bad Request
Date: Wed, 24 Jun 2015 23:10:52 GMT
Server: Apache/2.4.6 (Red Hat Enterprise Linux) PHP/5.6.10
X-Powered-By: PHP/5.6.10
Cache-Control: no-cache, private
Content-Length: 111
Connection: close
Content-Type: application/json

{"errors":[{"status":400,"title":"Bad Request","detail":"The request cannot be fulfilled due to bad syntax."}]}
```

what am I doing wrong ?

**Comment by jbrooksuk** [comment]
Thanks for the bug report! This is now fixed :)

**Comment by unixengineer** [comment]
@jbrooksuk I did a fresh pull, and set it up again, but I am still getting the same error:

```
# curl -X POST -H 'Accept: */*' -H "accept-encoding: gzip" -H "Content-Type: application/json" -H "X-Cachet-Token: 9yMHsdioQosnyVK4iCVR" http://localhost/api/v1/incidents -d '{
name: "Monkey Farts",
message: "The title says it all",
status: 1,
component_id: 1,
}'


{"errors":[{"status":400,"title":"Bad Request","detail":"The request cannot be fulfilled due to bad syntax."}]}
```

**Comment by jbrooksuk** [comment]
Are you using Postgres, MySQL or SQLite?

**Comment by unixengineer** [comment]
@jbrooksuk MySQL (5.6)

**Comment by jbrooksuk** [comment]
I've just tried the demo and it works (also using Paw):

Request:

```
POST /api/v1/incidents HTTP/1.1
X-Cachet-Token: 9yMHsdioQosnyVK4iCVR
Content-Type: application/json
Cookie: __cfduid=d65c54b052f92169f515864c9a118770f1435218005
Host: demo.cachethq.io
Connection: close
User-Agent: Paw/2.2.1 (Macintosh; OS X/10.10.3) GCDHTTPRequest
Content-Length: 85

{"name":"Monkey Farts","message":"The title says it all","status":1,"component_id":1}
```

Response:
```
HTTP/1.1 200 OK
Server: cloudflare-nginx
Date: Thu, 25 Jun 2015 18:15:37 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: close
Cache-Control: no-cache
Set-Cookie: laravel_session=eyJpdiI6IkZwaEI0V1FFSUhuTnNYaDdmbGwxY1VyWFh3K2FIalVCUUtDRzlXMDBhRnM9IiwidmFsdWUiOiJ6OWlhNkIyNzMrTStXNlwva09FOWRUSkdJWExFQlNJMlYyT2tjR3dpaXFpeHBqK0tVSnp1dkJuNEdZeU54RzR3d0FzUURMXC8wNStweG8raFArNFNrQWVnPT0iLCJtYWMiOiIwN2RiN2Y4NzVjYjc4ZjMwZmZmYTI5NjFlZWYxNWY2ZTQ3YmFmMjIzYzQ2OWI3OTg5YmE2ODBlN2JmYjgxMDA2In0%3D; expires=Thu, 25-Jun-2015 20:15:37 GMT; Max-Age=7200; path=/; httponly
Strict-Transport-Security: max-age=0; includeSubDomains; preload
X-Content-Type-Options: nosniff
CF-RAY: 1fc2a8a8177e061c-LHR

{"data":{"name":"Monkey Farts","message":"The title says it all","status":"1","component_id":"1","visible":1,"updated_at":"2015-06-25 19:15:37","created_at":"2015-06-25 19:15:37","id":4,"human_status":"Investigating","scheduled_at":"2015-06-25 19:15:37"}}
```

**Comment by unixengineer** [comment]
Thanks. It looks like I had an issue with curl.

**Comment by jbrooksuk** [comment]
:)

**Comment by unixengineer** [comment]
Thanks @jbrooksuk. 
whats weird is that, curl works now, but I am using the cachet-monitor tool, and that throws the same error.

**Comment by jbrooksuk** [comment]
You'll need to open an issue on `cachet-monitor` for that :)
