### ISSUE TITLE
Dashboard Errors

### ISSUE THREAD

**Issue by TheoBearman** [cachethq/Cachet#828]
There are a few dashboard errors, both on the Demo site and on my install.

When navigating to the Subscribers section:

![error1](https://cloud.githubusercontent.com/assets/6546590/8934930/06fad840-3542-11e5-87cb-da030af88f31.PNG)

Settings is not clickable in the left-hand nav bar because it is being hidden by the logo. When trying to navigate to the settings page using the URL, the following error appears:

![error2](https://cloud.githubusercontent.com/assets/6546590/8934963/2bad8836-3542-11e5-9803-4efe0ac87407.PNG)

Thanks,

Theo

**Comment by jbrooksuk** [comment]
Thanks Theo - this is fixed!

**Comment by TheoBearman** [comment]
My pleasure as always.

**Comment by TheoBearman** [comment]
@jbrooksuk It seems 'Settings'  is still being hidden by the Cachet logo. The 405 issue is still present so  I can't just navigate to it through the URL:


![nav](https://cloud.githubusercontent.com/assets/6546590/8936323/6ba4364a-3549-11e5-820c-fe06c73da115.PNG)

**Comment by jbrooksuk** [comment]
I know, I know - @GrahamCampbell tells me about this all of the time. I'm going to remove the logo for shallow screens :)

**Comment by jbrooksuk** [comment]
New issue please!
