### ISSUE TITLE
Docker: Database [{{DB_DRIVER}}] not configured when starting cachet container

### ISSUE THREAD

**Issue by svenmueller** [cachethq/Cachet#874]
Hi,

Since i pulled the latest docker image we get the following error when starting cachet:

```
Database [{{DB_DRIVER}}] not configured.
```

in the systemd unit file we also added the variable to pass it into the container:

```bash
ExecStart=/usr/bin/bash -c \
"/usr/bin/docker run --name cachet-migration --link mysql-db-cachet:mysql \
-e DB_HOST=mysql \
-e DB_DRIVER=$DB_DRIVER \
-e DB_DATABASE=$DB_DATABASE \
-e DB_USERNAME=$DB_USERNAME \
-e DB_PASSWORD=$DB_PASSWORD \
cachethq/cachet:latest php artisan migrate --force"
```
Any ideas?

Thx Sven

**Comment by jbrooksuk** [comment]
@n0mer and @wfjsw any ideas?

**Comment by n0mer** [comment]
@svenmueller 

what if you explicitly do

```
-e DB_DRIVER=mysql
```

**Comment by rtrauntvein** [comment]
I believe it will work if you do:

```
ExecStart=/usr/bin/bash -c \
"/usr/bin/docker run --name cachet-migration --link mysql-db-cachet:mysql \
-e DB_HOST=mysql \
-e DB_DRIVER=$DB_DRIVER \
-e DB_DATABASE=$DB_DATABASE \
-e DB_USERNAME=$DB_USERNAME \
-e DB_PASSWORD=$DB_PASSWORD \
cachethq/cachet:latest"

docker exec -it cachet-migration php artisan migrate --force

```

The entrypoint script needs to run to clear the cache and set up the .env properly

**Comment by jbrooksuk** [comment]
Closing this and leaving it with you.

**Comment by svenmueller** [comment]
i removed to current container and pulled the latest cachet image. how can this be a cache problem then?

@rtrauntvein can you elaborate why i should use `docker exec` here? I sticked to the commands shown in the `README.MD` to run the DB migration

**Comment by rtrauntvein** [comment]
Because at build time on docker hub it caches the .env template - The entrypoint.sh runs a `/usr/bin/php composer.phar install --no-dev -o` which clears the cache. I don't really know or understand Laravel so this is how I hacked it to work in docker. 

I guess you could do `docker exec -it <containerid> /usr/bin/php composer.phar install --no-dev -o` also

The README for running it in docker manually is essentially out of date and wrong.  When I re-wrote the docker setup to actually utilize a `.env` file I only tested that docker-compose instructions are valid (running `php artisan migrate --force` via docker exec)

**Comment by svenmueller** [comment]
@rtrauntvein thx for the details! :+1: 

i just tried both commands without luck:

```bash
$ docker exec -it cachet php artisan migrate --force
Nothing to migrate.
```
or

```bash
$ docker exec -it cachet /usr/bin/php composer.phar install --no-dev -o
> rm -f compiled.php config.php routes.php services.json
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
> php artisan optimize --force
Generating optimized class loader
Compiling common classes
> php artisan config:cache
Configuration cache cleared!
Configuration cached successfully!
> php artisan route:cache
Route cache cleared!
Routes cached successfully!
> chmod -R 755 storage
```

I still get an error when running migrations:
```bash
$ fleetctl journal cachet-migration
-- Logs begin at Sat 2015-06-27 02:46:12 UTC, end at Thu 2015-08-06 18:56:42 UTC. --
Aug 06 18:54:25 status docker[15980]: cachet-migration
Aug 06 18:54:25 status docker[15988]: cachet-migration
Aug 06 18:54:25 status systemd[1]: Started Create an migrate database tables for status application.
Aug 06 18:54:27 status bash[16001]: [InvalidArgumentException]
Aug 06 18:54:27 status bash[16001]: Database [{{DB_DRIVER}}] not configured.
Aug 06 18:54:27 status systemd[1]: cachet-migration.service: Main process exited, code=exited, status=1/FAILURE
Aug 06 18:55:04 status systemd[1]: Stopped Create an migrate database tables for status application.
Aug 06 18:55:04 status systemd[1]: cachet-migration.service: Unit entered failed state.
Aug 06 18:55:04 status systemd[1]: cachet-migration.service: Failed with result 'exit-code'.
Aug 06 18:55:04 status systemd[1]: Stopping Create an migrate database tables for status application...
```

currently we are not able to run dockerized cachet for our production environment. can we open this issue again please?

**Comment by rtrauntvein** [comment]
Looks like you need to run it against your `cachet-migration` container.

I opened PR #878 which should fix the README

**Comment by svenmueller** [comment]
@rtrauntvein thx, just tried that too, but the error persists

```bash
$ docker exec -it cachet-migration php artisan migrate --force
Nothing to migrate.
```

**Comment by rtrauntvein** [comment]
Are you sure it hasn't completed then? That is the message you receive if it has already been done.

First time:
```
$ docker exec -it cachet php artisan migrate --force
Migration table created successfully.
Migrated: 2015_01_05_201324_CreateComponentGroupsTable
Migrated: 2015_01_05_201444_CreateComponentsTable
Migrated: 2015_01_05_202446_CreateIncidentTemplatesTable
Migrated: 2015_01_05_202609_CreateIncidentsTable
Migrated: 2015_01_05_202730_CreateMetricPointsTable
Migrated: 2015_01_05_202826_CreateMetricsTable
Migrated: 2015_01_05_203014_CreateSettingsTable
Migrated: 2015_01_05_203235_CreateSubscribersTable
Migrated: 2015_01_05_203341_CreateUsersTable
Migrated: 2015_01_09_083419_AlterTableUsersAdd2FA
Migrated: 2015_01_16_083825_CreateTagsTable
Migrated: 2015_01_16_084030_CreateComponentTagTable
Migrated: 2015_02_28_214642_UpdateIncidentsAddScheduledAt
Migrated: 2015_05_19_214534_AlterTableComponentGroupsAddOrder
Migrated: 2015_05_20_073041_AlterTableIncidentsAddVisibileColumn
Migrated: 2015_05_24_210939_create_jobs_table
Migrated: 2015_05_24_210948_create_failed_jobs_table
Migrated: 2015_06_10_122216_AlterTableComponentsDropUserIdColumn
Migrated: 2015_06_10_122229_AlterTableIncidentsDropUserIdColumn
Migrated: 2015_08_02_120436_AlterTableSubscribersRemoveDeletedAt
```

Second time:
```
$ docker exec -it cachet php artisan migrate --force
Nothing to migrate.
```

**Comment by svenmueller** [comment]
Before wa start the cachet container, we start a container doing the db migration. So yes, the tables  should be migrated.

but the migration exits with `status=1`

```bash
$ fleetctl journal cachet-migration
-- Logs begin at Sat 2015-06-27 02:46:12 UTC, end at Thu 2015-08-06 19:15:19 UTC. --
Aug 06 19:07:37 status bash[17434]: 2015-08-06 19:07:37,657 INFO stopped: php5-fpm (exit status 0)
Aug 06 19:07:37 status bash[17434]: 2015-08-06 19:07:37,683 INFO stopped: nginx (exit status 0)
Aug 06 19:07:38 status systemd[1]: Stopped cachet-migration.service.
Aug 06 19:07:54 status systemd[1]: Starting Create an migrate database tables for status application...
Aug 06 19:07:54 status docker[17976]: cachet-migration
Aug 06 19:07:54 status systemd[1]: Started Create an migrate database tables for status application.
Aug 06 19:07:54 status docker[17982]: cachet-migration
Aug 06 19:07:54 status bash[17990]: [InvalidArgumentException]
Aug 06 19:07:54 status bash[17990]: Database [{{DB_DRIVER}}] not configured.
Aug 06 19:07:54 status systemd[1]: cachet-migration.service: Main process exited, code=exited, status=1/FAILURE
```

here is the unit file for starting the cachet-migration container (runs before the cachet container is started):

```bash
[Unit]
Description=Create an migrate database tables for status application
After=mysql-db@cachet.service
Requires=mysql-db@cachet.service

[Service]
RemainAfterExit=yes
# Get CoreOS environmental variables
EnvironmentFile=/etc/environment
TimeoutStartSec=0
ExecStartPre=-/usr/bin/docker kill cachet-migration
ExecStartPre=-/usr/bin/docker rm cachet-migration
ExecStartPre=/usr/bin/docker pull cachethq/cachet:latest
ExecStart=/usr/bin/bash -c \
"/usr/bin/docker run --name cachet-migration --link mysql-db-cachet:mysql \
-e DB_HOST=mysql \
-e DB_DRIVER=$DB_DRIVER \
-e DB_DATABASE=$DB_DATABASE \
-e DB_USERNAME=$DB_USERNAME \
-e DB_PASSWORD=$DB_PASSWORD \
cachethq/cachet:latest php artisan migrate --force"

[X-Fleet]
MachineOf=mysql-db@cachet.service
```

**Comment by rtrauntvein** [comment]
Because you are overriding the entrypoint.sh with the `php artisan migrate --force` the setting of the `.env` is never happening.  This is why you see `{{DB_DRIVER}}` in the logs because the `.env` is not getting populated and then clearing the cache - This is what the entrypoint.sh script does.

May be possible to do:

`docker run ... cachethq/cachet:latest entrypoint.sh && php artisan migrate --force`

**Comment by svenmueller** [comment]
@rtrauntvein thx a lot! when executing `docker run ... cachethq/cachet:latest entrypoint.sh && php artisan migrate --forc` the error complaining about `{{DB_DRIVER}}` disappaers

**Comment by jbrooksuk** [comment]
@rtrauntvein @wfjsw @n0mer can you email me at james@alt-three.com please.

**Comment by glaszig** [comment]
```
# docker run -it --rm --link mysql:mysql -e DB_DRIVER=mysql -e DB_HOST=mysql -e DB_DATABASE="cachet" -e DB_USERNAME="cachet" -e DB_PASSWORD="cachet" "cachethq/cachet:latest" php artisan migrate --force
Unable to find image 'cachethq/cachet:latest' locally
latest: Pulling from cachethq/cachet
01f4eb5b6340: Pull complete
d6102a5f384b: Pull complete
a5f1a77671e0: Pull complete
9c7b2e5cf12e: Pull complete
9c59a5c1c534: Pull complete
2a9daf6f4834: Pull complete
48d030f414d5: Pull complete
017953ef929e: Pull complete
4cc9265381e1: Pull complete
79f1482dee2e: Pull complete
83121a8d4295: Already exists
902b87aaaec9: Already exists
9a61b6b1315e: Already exists
Digest: sha256:8100a2c92ea685d79ecf8b2f0c9d2f246ae3a24b7a85fae47a3b35b51bca9666
Status: Downloaded newer image for cachethq/cachet:latest



  [InvalidArgumentException]
  Database [{{DB_DRIVER}}] not configured.


```

anybody figured this out?

**Comment by jbrooksuk** [comment]
@cachethq/docker

**Comment by n0mer** [comment]
@glaszig read few comments above:

"docker run ... cachethq/cachet:latest entrypoint.sh && php artisan migrate --force"

you have to prepend `entrypoint.sh`

**Comment by glaszig** [comment]
@n0mer alright. that worked. now, that might be off topic, i'm getting a laravel exception (in the browser): 

```
RuntimeException
No supported encrypter found. The cipher and / or key length are invalid.
```

(i've read somewhere that an invalid APP_KEY might be the reason but that env var is set properly.)

**Comment by svenmueller** [comment]
@glaszig i went through the same pain. Simply pass `APP_KEY` with 32 chars as environment variable (see https://github.com/cachethq/Cachet/blob/b1600bdbee856891d5d82fef63004143d05751a9/config/app.php#L90)

**Comment by n0mer** [comment]
@wfjsw probably entrypoint.sh can be set as docker `ENTRYPOINT` command, not `RUN` - this way it will always be executed.

`entrypoint.sh` should be modified - everything that is passes as parameter should be then executed as a command. This way there will be no need for `&&`

**Comment by glaszig** [comment]
@svenmueller thanks. appears to work.

@n0mer prefixing `entrypoint.sh` starts up the stack. but what i want is to run the migrations which does not happen because of `entrypoint.sh`. `--entrypoint /sbin/entrypoint.sh` does not make any difference.

**Comment by n0mer** [comment]
@glaszig i always run migrations by entering running container (that was previously started).

Then just `php artisan migrate --force` insude running container

**Comment by n0mer** [comment]
@svenmueller since `APP_KEY` appears to be mandatory param, then `entrypoint.sh` should react properly with ERROR/WARN message if this env. var. is not set.

@wfjsw what do you think?

**Comment by glaszig** [comment]
@n0mer oh. that works, of course.

ok. for everyone, here's my command sequence to get this up and running (omitting mysql container setup):

**start the cachet container**
```
# docker run -d --name cachet --link mysql:mysql -e DB_DRIVER=mysql -e DB_HOST=mysql -e DB_DATABASE="cachet" -e DB_USERNAME="cachet" -e DB_PASSWORD="cachet" -e APP_KEY=<your-app-key> -p 8000:8000 --entrypoint /sbin/entrypoint.sh "cachethq/cachet:latest"
```

**run migrations inside this container**

```
# docker exec -it cachet php artisan migrate --force
Migration table created successfully.
Migrated: 2015_01_05_201324_CreateComponentGroupsTable
Migrated: 2015_01_05_201444_CreateComponentsTable
Migrated: 2015_01_05_202446_CreateIncidentTemplatesTable
Migrated: 2015_01_05_202609_CreateIncidentsTable
Migrated: 2015_01_05_202730_CreateMetricPointsTable
Migrated: 2015_01_05_202826_CreateMetricsTable
Migrated: 2015_01_05_203014_CreateSettingsTable
Migrated: 2015_01_05_203235_CreateSubscribersTable
Migrated: 2015_01_05_203341_CreateUsersTable
Migrated: 2015_01_09_083419_AlterTableUsersAdd2FA
Migrated: 2015_01_16_083825_CreateTagsTable
Migrated: 2015_01_16_084030_CreateComponentTagTable
Migrated: 2015_02_28_214642_UpdateIncidentsAddScheduledAt
Migrated: 2015_05_19_214534_AlterTableComponentGroupsAddOrder
Migrated: 2015_05_20_073041_AlterTableIncidentsAddVisibileColumn
Migrated: 2015_05_24_210939_create_jobs_table
Migrated: 2015_05_24_210948_create_failed_jobs_table
Migrated: 2015_06_10_122216_AlterTableComponentsDropUserIdColumn
Migrated: 2015_06_10_122229_AlterTableIncidentsDropUserIdColumn
Migrated: 2015_08_02_120436_AlterTableSubscribersRemoveDeletedAt
```

**Comment by wfjsw** [comment]
@n0mer 
We use `-d` in docker, that means when fails, the container died silently and ERR & WARNs in `entrypoint.sh` will only show up when execute `docker logs`. but do output the error is far better than warn nothing. We can add some `if` in entrypoint.sh. Also make a way to mount .env by volume.

**Comment by wfjsw** [comment]
@glaszig I will document this way to readme. I strongly recommend this over the original one.

**Comment by n0mer** [comment]
@wfjsw @glaszig please also add version without `--link mysql:mysql`

And, why not use `entrypoint.sh` as Docker's `ENTRYPOINT`? This way it will always be called.

@jbrooksuk to Cachet developers - what about better error message if `APP_KEY` env variable is not set? Something more user-friendly than 

```
RuntimeException
No supported encrypter found. The cipher and / or key length are invalid.
```

**Comment by jbrooksuk** [comment]
That's a default Laravel error.

Cachet Version 2.0 will be making installation **much** easier so this should become a non-issue.

**Comment by n0mer** [comment]
Maybe, but automatic bootstrap will still require almost the same set of configuration parameters. 
And bash script-driven automatic will, most probably, not benefit at all from install wizard.

If new version of underlying `Laravel` framework will throw more human-friendly errors - that's fine.
